name: myLintAction
description: Runs a python linter 

inputs:
  target:
    description: 'The target to lint'
    required: true
    default: ${{ github.workspace }}
  
runs:
  using: 'composite'
  steps:
    - name: Installation de python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Installation des dépendances
      run: pip install -r requirements.txt
      shell: bash

    - name: Verification des types
      run: mypy calculs
      shell: bash

    - name: Correction du formattage
      run: black calculs tests
      shell: bash

    - name: Check quality
      run: flake8 calculs tests
      shell: bash