name: Delivery workflow

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

env:
  REPO: ""
  
jobs:
  build_and_push:
    name: docker delivery with watchtower

    runs-on: ubuntu-24.04

    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name:  Login to Github Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9z82s7399ccc52663121
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Setup Docker
        uses: docker/setup-docker-action@v5
        
      - name: Build and push
        uses: docker/build-push-action/v7.1.0
        with:
          context:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ github.sha}}
            ghcr.io/${{ env.REPO }}:latest
          cache-from: type-gha
          cache-to: type-gha,mode-max

    

