name: Pipeline CICD

on:
  push:


jobs: 
  compilation:
    name: job de compilation
    runs-on: ubuntu-24.04

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # - name: Installation des dépendances
      #   run: pip install -r requirements.txt

      - name: Execution du programme
        run: python main.py

  test:
    name: job de test
    runs-on: ubuntu-24.04
    needs: compilation

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Execution des tests
        run: pytest --cov=calculs --cov-report=term-missing

  linting:
    name: verification du lint
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - run: echo "Verification du lint"


  build:
    name: build project
    runs-on: ubuntu-24.04
    needs: linting

    steps:
      - run: echo "Le projet build"


  succes:
    name: succes pipeline
    runs-on: ubuntu-slim
    needs: [compilation, test, linting, build]
    steps:
      - run: echo "La pipeline est validée"

