name: Pipeline CICD

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]



jobs: 
  compilation:
    name: job de compilation

    strategy:
      matrix:
        python_version: ["3.12", "3.13" ,"3.14"]
        os_version : [ ubuntu-22.04, ubuntu-24.04]


    runs-on: ${{ matrix.os_version}}

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Execution du programme
        run: python main.py

  linting:
    name: verification du lint
    needs: compilation

    strategy:
      matrix:
        python_version: ["3.12", "3.13" ,"3.14"]
        
    runs-on: ubuntu-24.04

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Verification des types
        run: mypy calculs

      - name: Correction du formattage
        run: black calculs tests

      - name: Check quality
        run: flake8 calculs tests

  test:
    name: job de test
    needs: linting


    strategy:
      matrix:
        python_version: ["3.12", "3.13" ,"3.14"]
        os_version : [ ubuntu-22.04, ubuntu-24.04]


    runs-on: ${{ matrix.os_version}}

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Execution des tests
        run: pytest --cov=calculs --cov-report=term-missing

      - name: Check du coverage
        run: pytest --cov=calculs --cov-report=term-missing --cov-fail-under=90


  build:
    name: build project
    needs: test

    strategy:
      matrix:
        python_version: ["3.12", "3.13" ,"3.14"]
        os_version : [ ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os_version}}

    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}


      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Mise en place du build
        run: pyinstaller --onefile --name calculs-snapshot main.py 
    
      - name: Vérification présence du build
        run: ls dist/

  call-reusable-workflow:
    name: Appel d'un workflow réutilisable
    uses: nowone33/cicd_python/.github/workflows/reusable.yml@feature/newWorkflow
    with:
      name: ${{ github.actor }}

  succes:
    name: succes pipeline
    runs-on: ubuntu-slim
    needs: [compilation, test, linting, build]
    steps:
      - name: La pipeline est elle validée ?
        run: echo "La pipeline est validée"



